In [1]:
import pandas as pd

import numpy as np
import os

In [2]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', 200)
pd.options.display.float_format = '{:,.6f}'.format

In [3]:
os.getcwd()

'/media/eduseiti/bigdata01/unicamp/ia368v_dd/unicamp_IR'

In [32]:
RETRIEVALS_FOLDER="/media/eduseiti/bigdata01/unicamp/ia368v_dd/trabalho_final/validation_queries_retrievals"

COLBERTX_FOLDER="/media/eduseiti/bigdata01/unicamp/ia368v_dd/trabalho_final/clueweb22-pt_10M_sample_fixed"
# RETRIEVALS_FOLDER="validation_queries_retrievals"

### Check BM25 + mT5 retrieval

In [5]:
mT5_df = pd.read_csv(os.path.join(RETRIEVALS_FOLDER, "200-queries-passagens-by-BM25-mT5_v4.tsv"), sep="\t")

In [6]:
mT5_df

,query,doc_id,passage-by-bm25-mt5
0,Qual objetivo da Enel Brasil?,clueweb22-pt0000-58-10513_2,"Sendo assim, em linha com o modelo de Criação de Valor Compartilhado (Creating Shared Value - CSV) adotado pela companhia mundialmente, temos o objetivo de associar o desenvolvimento do nosso negócio às necessidades das comunidades brasileiras e realizamos diversas iniciativas para possibilitar a geração de renda, como cursos, oficinas e outros projetos sociais. Além disso, nos comprometemos explicitamente a alcançar quatro dos 17 Objetivos de Desenvolvimento Sustentável (ODS) da ONU: amplo acesso à energia limpa e acessível, apoio à educação de qualidade, contribuição para o desenvolvimento socioeconômico e combate contra as alterações climáticas. Conheça o novo site da Enel Brasil Selecione o seu Estado: RIO DE JANEIRO CEARÁ GOIÁS SÃO PAULO Não é cliente Enel? Clique aqui e conheça o nosso Grupo"
1,Qual objetivo da Enel Brasil?,clueweb22-pt0000-81-12555_1,"A Enel Brasil foi constituída em 2005 com o objeto de centralizar as participações societárias do grupo Enel no país e criar, por meio de uma holding de empresas, uma plataforma sólida de gestão dos ativos que preparasse a companhia para futuras expansões. Em 2007, a Enel SpA, controladora indireta da Enel Brasil, iniciou a consolidação de sua participação sobre a holding brasileira. Por meio de uma oferta pública no exterior, a Enel SpA adquiriu a totalidade das ações de emissão da espanhola Endesa – na época acionista controladora indireta da Enel Brasil. Em 2009, o controle da Enel SpA sobre a Enel Brasil foi ampliado, com a aquisição de 92,06% do capital social e votante da Endesa. Finalmente, em 2014, a Enel SpA adquiriu – por meio de uma operação de compra e venda de ações – a participação da Endesa em sociedades na América Latina, o que incluiu a Enel Brasil. Desde então, a empresa espanhola foi excluída da estrutura acionária no país. Apesar da holding Enel Brasil ter nascido em 2005, a trajetória do grupo Enel no país começou quase uma década antes, em 1996, com a aquisição da distribuidora de energia elétrica CERJ em leilão de privatização. Novas aquisições foram realizadas ao longo dos anos, garantindo a ampliação e diversificação do portfólio."
2,Qual objetivo da Enel Brasil?,clueweb22-pt0000-39-18411_1,"Inovação e Sustentabilidade inovação Cultura da Inovação Saiba mais sobre como a Cultura da Inovação é fundamental para transformar a inovação na Enel. Sustentabilidade Nossos Compromissos Nosso objetivo: deixar um mundo melhor e mais sustentável para as gerações futuras. Sustentabilidade Relatórios anuais Conheça nossos principais indicadores, estratégias, iniciativas e resultados. SUSTENTABILIDADE Nossas Iniciativas Referência em sustentabilidade, o Ecoenel alia gestão ambiental, social e tecnologia. Notícias Veja Mais Notícias Nossa Energia para um amanhã melhor Estamos realizando manutenções noturnas no Rio de Janeiro Unidos pela vacina: A Enel Brasil abraça essa causa! Conheça o novo site da Enel Brasil Selecione o seu Estado: RIO DE JANEIRO CEARÁ GOIÁS SÃO PAULO Não é cliente Enel? Clique aqui e conheça o nosso Grupo"
3,Qual objetivo da Enel Brasil?,clueweb22-pt0002-00-04601_1,"inovação Cultura da Inovação Saiba mais sobre como a Cultura da Inovação é fundamental para transformar a inovação na Enel. Sustentabilidade Nossos Compromissos Nosso objetivo: deixar um mundo melhor e mais sustentável para as gerações futuras. Sustentabilidade Relatórios anuais Conheça nossos principais indicadores, estratégias, iniciativas e resultados. SUSTENTABILIDADE Nossas Iniciativas Referência em sustentabilidade, o Ecoenel alia gestão ambiental, social e tecnologia. Notícias Veja Mais Notícias Nossa Energia para um amanhã melhor Estamos realizando manutenções noturnas no Rio de Janeiro Unidos pela vacina: A Enel Brasil abraça essa causa! Conheça o novo site da Enel Brasil Selecione o seu Estado: RIO DE JANEIRO CEARÁ GOIÁS SÃO PAULO Não é cliente Enel? Clique aqui e conheça o nosso Grupo"
4,Qual objetivo da Enel Brasil?,clueweb22-pt0000-58-10513_0,"Enel no Brasil: inovação tecnológica e sustentabilidade ambiental Somos a maior empresa privada do setor elétrico brasileiro e desempenhamos papel de liderança no desenvolvimento das fontes renováveis de energia no país. Atuamos em toda a cadeia energética, com atividades nas áreas de geração, distribuição, transmissão e comercialização, além de soluções em energia. Por meio de quatro distribuidoras, nos estados do Rio de Janeiro, Ceará, Goiás e São Paulo, levamos energia a 18,3 milhões de clientes residenciais, comerciais, industriais, rurais e do setor público. No segmento de geração, a companhia também é o maior operador de energia solar e eólica do Brasil em termos de capacidade instalada, gerenciando ao todo uma capacidade renovável total de mais de 4,3 GW, dos quais mais de 1,8 GW são de fonte eólica, cerca de 1,2 GW são de fonte solar e cerca de 1,3 GW de hidro. Temos, ainda em geração, Pequenas Centrais Hidrelétricas (PCH’s) em diversos estados, uma usina hidrelétrica em Goiás e uma usina termoelétrica de ciclo combinado (gás e vapor) no Ceará."
...,...,...,...
199995,Que receitas eu posso fazer com 5 ingredientes?,clueweb22-pt0001-20-08083_10,"Convide os pais ou responsáveis a conversarem com as crianças sobre a receitas favoritas das pessoas da família. De forma que as crianças e cada membro possam contar qual é a receita e porque gostam tanto dela. Sugira que, depois de falarem sobre as preferências alimentares, elejam qual é a favorita de toda a família, numa votação simples. Proponha que, junto das crianças, façam desenhos dessa receita, assim, poderão conversar com elas sobre os ingredientes e o modo de fazer. Depois, podem expor os desenhos em algum lugar da casa que fique visível à todos. Para compartilhar com o grupo Convide as famílias a compartilhar a receita e os desenhos de modo que você possa agrupá-los e partilhá-los com as outras famílias. Sugira a construção de um compilado de receitas favoritas da turma, que poderá ser compartilhado via Documentos Google ou por WhatsApp. As famílias poderão testá-las em outros momentos de convívio familiar. Você pode fazer uma indicação de sua receita favorita também! No retorno à escola, as crianças podem confeccionar um livro de receitas da turma. Sobre o plano Este plano de atividade foi elaborado pelo Time de Autores NOVA ESCOLA Autor: Sandra Bonotto Mentor: Wildes Gomes de Campos Especialista do subgrupo etário: Karina Rizek"
199996,Que receitas eu posso fazer com 5 ingredientes?,clueweb22-pt0000-12-13275_2,"Publicidade Conselhos e Truques Você sabia que tem 30 motivos para parar de tomar leite de vaca? Receitas sem Fronteiras Emagrecimento: como manter o déficit calórico com saúde IstoÉ Desinchando o corpo: 10 alimentos que combatem a retenção hídrica Sport Life Brasil 4 truques de limpeza para fazer uma faxina caprichada no feriado Aproveitando que estamos no meio de um feriado, pode ser uma ótima ideia fazer aquela faxina poderosa para deixar a casa em ordem e definir com calma as próximas metas. Afinal, não é sempre que temos tempo de realmente caprichar na limpeza do lar, não é mesmo? Mas, para que essa faxina caprichada seja uma pouco mais rápida de fazer e você possa pas... Alto Astral Covid-19: 5 fatores que podem ameaçar o fim da emergência de saúde… Chegada do inverno, descoberta de novas variantes, surtos em outros países, desestruturação dos serviços e queda de proteção da vacina são alguns dos ingredientes que precisam ser observados de perto nas próximas semanas. BBC News Pílula anticoncepcional masculina deve começar a ser testada este ano…"
199997,Que receitas eu posso fazer com 5 ingredientes?,clueweb22-pt0000-00-21229_1,"Escolha um plano Para 2 pessoas R$ 59,00 / quinzena + frete (10,00) Para 4 pessoas R$ 116,00 / quinzena + frete (10,00) para 2 pessoas Receba, em sua casa, uma receita para 2 ou 4 pessoas de 15 em 15 dias. Valor para 2 pessoas: R$ 59,00 + frete (10,00) R$ 29,50 por pessoa Assinar The Market para 2 pessoas Sem Amarras! Cancele ou Pause a sua assinatura quando quiser. O que Dizem as Boas Línguas ""Encomendei para o final de semana para que meu marido, que nunca cozinhou, fizesse. Ficou excelente! Os ingredientes bem selecionado, frescos e de qualidade, Parabéns!! "" Luciana Galvão ""Tudo ótimo, desde a atenção na entrega do pedido até a qualidade da matéria prima. Depois, me ligaram para saber como foi e se eu tinha gostado. Amei e recomendo com certeza! Pedirei outras vezes ;)"" Camila Shinada ""Posso dizer seguramente: o The Market me ensinou a cozinhar! Todos os pratos que comprei estavam excelentes. Fáceis de fazer e deliciosos! 100% aprovado! Parabéns!"" Guilherme Oliveira ""Excelente, tenho gostado mais a cada receita que recebo e estou sempre divulgando a ideia. Depois que consegui fazer um Beef Wellington, percebi que posso fazer tudo na cozinha. Parabéns pela idéia"" Sidnei Junior"
199998,Que receitas eu posso fazer com 5 ingredientes?,clueweb22-pt0000-37-04796_7,"5 anos atrás 200 ml no Brasil é copo americano, rsrs Responder Hugo 5 anos atrás Um cup (medida americana) é mais uns 220ml :D mas sim estás perto o suficiente heheheh Maria Rita 5 anos atrás Olá, seguir essa receita à risca, é interessante as medidas serem em gramas, pois isso deixa pouca margem de erro. A foto da receita passa a imagem de um bolo úmido e leve, os ingredientes e o método indicam sabor. Mas isso não aconteceu quando fiz o bolo, é um bolo comum, o sabor a textura ficam longe do que mostra a foto. Foto x receita enganam muito. Responder Hugo 5 anos atrás Nós tentamos sempre usar gramas quanto possível exatamente por essa razão, no entanto esta receita não foi feita por mim, foi enviada para o Iguaria de qualquer forma posso fazer a receita e ver se fica igual ou não e atualizar as fotos! :D beatriz 4 anos atrás úmido, NÃO tem H. por favor,……….. Responder Hugo 4 anos atrás"
199999,Que receitas eu posso fazer com 5 ingredientes?,clueweb22-pt0001-84-06499_18,"As batedeiras planetárias oferecem a variedade de acessórios para cada tipo de receita, é importante que utilize as que forem mais vantajosas para a sua receita. Para aqueles que investem em receitas maiores tenha tigelas extras para não perder tempo lavando a única que tem e possa fazer a receita o breve possível, evitando também, a mistura indesejada de ingredientes. Um misturador de silicone auxiliará na mistura sem que precise fazer manualmente, o que facilitará o trabalho da receita e a mistura dos ingredientes. Melhores Batedeiras Planetárias Uma batedeira pode ser facilmente uma das compras mais excitantes que você irá fazer para a sua cozinha, especialmente se você assar muito. Como essa é uma peça de investimento, a maioria das pessoas realmente quer ter certeza de que tem o espaço, o dinheiro e a necessidade de uma batedeira desse tipo antes de comprar. É quase impossível encontrar a melhor batedeira apenas olhando para embalagem ou lendo especificações de manual. A maioria dos fabricantes anuncia motores com potência impressionantes."

### Add query ID

In [7]:
queries_01_df = pd.read_csv(os.path.join(RETRIEVALS_FOLDER, "queries_validation.tsv"), sep='\t', names=['query_id', 'query'])

In [8]:
queries_02_df = pd.read_csv(os.path.join(RETRIEVALS_FOLDER, "validation_queries_mirelle.tsv"), sep='\t', names=['query_id', 'query'])

In [9]:
queries_01_df.head()

   query_id                                                             query
0         0                  Qual a maior característica da flora brasileira?
1         1                  Qual a maior característica da fauna brasileira?
2         2  Por que os países Guiana e Suriname não são filiados a Conmebol?
3         3                              Por que a Bolívia tem duas capitais?
4         4                             Qual o que significa decolonialidade?

In [10]:
queries_02_df.head()

,query_id,query
0,100,Qual objetivo da Enel Brasil?
1,101,Qual a abordagem de mineração da moeda digital Chia (XCH)?
2,102,Quais produtos são revendidos pela empresa Casa da Coifa?
3,103,Em que ano surgiu a Universities and Colleges Admissions Service (UCAS)?
4,104,Quais etapas para a inscrição pelo Colleges Admissions Service (UCAS)?

In [11]:
mT5_df = mT5_df.merge(pd.concat([queries_01_df, queries_02_df]).reset_index(drop=True), left_on="query", right_on="query", how="outer")

In [12]:
mT5_df.head()

,query,doc_id,passage-by-bm25-mt5,query_id
0,Qual objetivo da Enel Brasil?,clueweb22-pt0000-58-10513_2,"Sendo assim, em linha com o modelo de Criação de Valor Compartilhado (Creating Shared Value - CSV) adotado pela companhia mundialmente, temos o objetivo de associar o desenvolvimento do nosso negócio às necessidades das comunidades brasileiras e realizamos diversas iniciativas para possibilitar a geração de renda, como cursos, oficinas e outros projetos sociais. Além disso, nos comprometemos explicitamente a alcançar quatro dos 17 Objetivos de Desenvolvimento Sustentável (ODS) da ONU: amplo acesso à energia limpa e acessível, apoio à educação de qualidade, contribuição para o desenvolvimento socioeconômico e combate contra as alterações climáticas. Conheça o novo site da Enel Brasil Selecione o seu Estado: RIO DE JANEIRO CEARÁ GOIÁS SÃO PAULO Não é cliente Enel? Clique aqui e conheça o nosso Grupo",100
1,Qual objetivo da Enel Brasil?,clueweb22-pt0000-81-12555_1,"A Enel Brasil foi constituída em 2005 com o objeto de centralizar as participações societárias do grupo Enel no país e criar, por meio de uma holding de empresas, uma plataforma sólida de gestão dos ativos que preparasse a companhia para futuras expansões. Em 2007, a Enel SpA, controladora indireta da Enel Brasil, iniciou a consolidação de sua participação sobre a holding brasileira. Por meio de uma oferta pública no exterior, a Enel SpA adquiriu a totalidade das ações de emissão da espanhola Endesa – na época acionista controladora indireta da Enel Brasil. Em 2009, o controle da Enel SpA sobre a Enel Brasil foi ampliado, com a aquisição de 92,06% do capital social e votante da Endesa. Finalmente, em 2014, a Enel SpA adquiriu – por meio de uma operação de compra e venda de ações – a participação da Endesa em sociedades na América Latina, o que incluiu a Enel Brasil. Desde então, a empresa espanhola foi excluída da estrutura acionária no país. Apesar da holding Enel Brasil ter nascido em 2005, a trajetória do grupo Enel no país começou quase uma década antes, em 1996, com a aquisição da distribuidora de energia elétrica CERJ em leilão de privatização. Novas aquisições foram realizadas ao longo dos anos, garantindo a ampliação e diversificação do portfólio.",100
2,Qual objetivo da Enel Brasil?,clueweb22-pt0000-39-18411_1,"Inovação e Sustentabilidade inovação Cultura da Inovação Saiba mais sobre como a Cultura da Inovação é fundamental para transformar a inovação na Enel. Sustentabilidade Nossos Compromissos Nosso objetivo: deixar um mundo melhor e mais sustentável para as gerações futuras. Sustentabilidade Relatórios anuais Conheça nossos principais indicadores, estratégias, iniciativas e resultados. SUSTENTABILIDADE Nossas Iniciativas Referência em sustentabilidade, o Ecoenel alia gestão ambiental, social e tecnologia. Notícias Veja Mais Notícias Nossa Energia para um amanhã melhor Estamos realizando manutenções noturnas no Rio de Janeiro Unidos pela vacina: A Enel Brasil abraça essa causa! Conheça o novo site da Enel Brasil Selecione o seu Estado: RIO DE JANEIRO CEARÁ GOIÁS SÃO PAULO Não é cliente Enel? Clique aqui e conheça o nosso Grupo",100
3,Qual objetivo da Enel Brasil?,clueweb22-pt0002-00-04601_1,"inovação Cultura da Inovação Saiba mais sobre como a Cultura da Inovação é fundamental para transformar a inovação na Enel. Sustentabilidade Nossos Compromissos Nosso objetivo: deixar um mundo melhor e mais sustentável para as gerações futuras. Sustentabilidade Relatórios anuais Conheça nossos principais indicadores, estratégias, iniciativas e resultados. SUSTENTABILIDADE Nossas Iniciativas Referência em sustentabilidade, o Ecoenel alia gestão ambiental, social e tecnologia. Notícias Veja Mais Notícias Nossa Energia para um amanhã melhor Estamos realizando manutenções noturnas no Rio de Janeiro Unidos pela vacina: A Enel Brasil abraça essa causa! Conheça o novo site da Enel Brasil Selecione o seu Estado: RIO DE JANEIRO CEARÁ GOIÁS SÃO PAULO Não é cliente Enel? Clique aqui e conheça o nosso Grupo",100
4,Qual objetivo da Enel Brasil?,clueweb22-pt0000-58-10513_0,"Enel no Brasil: inovação tecnológica e sustentabilidade ambiental Somos a maior empresa privada do setor elétrico brasileiro e desempenhamos papel de liderança no desenvolvimento das fontes renováveis de energia no país. Atuamos em toda a cadeia energética, com atividades nas áreas de geração, distribuição, transmissão e comercialização, além de soluções em energia. Por meio de quatro distribuidoras, nos estados do Rio de Janeiro, Ceará, Goiás e São Paulo, levamos energia a 18,3 milhões de clientes residenciais, comerciais, industriais, rurais e do setor público. No segmento de geração, a companhia também é o maior operador de energia solar e eólica do Brasil em termos de capacidade instalada, gerenciando ao todo uma capacidade renovável total de mais de 4,3 GW, dos quais mais de 1,8 GW são de fonte eólica, cerca de 1,2 GW são de fonte solar e cerca de 1,3 GW de hidro. Temos, ainda em geração, Pequenas Centrais Hidrelétricas (PCH’s) em diversos estados, uma usina hidrelétrica em Goiás e uma usina termoelétrica de ciclo combinado (gás e vapor) no Ceará.",100

#### Save the retrieval results with the query ID

In [13]:
mT5_df.to_csv(os.path.join(RETRIEVALS_FOLDER, "200-queries-passagens-by-BM25-mT5_v4_with_query_id.tsv"), sep='\t', index=False)

#### Check the merged result

In [ ]:
mT5_df.groupby('query_id').count()

In [ ]:
mT5_df['query_id'].unique()

In [ ]:
mT5_df['query'].unique().shape

### ColbertX retrievals

In [14]:
retrievals_000_099_df = pd.read_csv(os.path.join(RETRIEVALS_FOLDER, "colbertx_all_znormalized_validation_scores_000_099.tsv"), sep='\t')

In [20]:
np.sort(retrievals_000_099_df['query_id'].unique())

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:
retrievals_000_099_df.head()

,query_id,colbertx_id,doc_position,doc_score,score_znorm,part,clueweb_id
0,0,4138910,1,28.797396,3.723518,2,clueweb22-pt0000-86-19982_33
1,1,4138910,1,28.135212,3.365722,2,clueweb22-pt0000-86-19982_33
2,25,4138910,671,21.382965,-0.282701,2,clueweb22-pt0000-86-19982_33
3,26,4138910,476,20.872330,-0.558611,2,clueweb22-pt0000-86-19982_33
4,54,4138910,31,26.231224,2.336945,2,clueweb22-pt0000-86-19982_33

In [16]:
retrievals_000_099_df.groupby('query_id').count()

          colbertx_id  doc_position  doc_score  score_znorm   part  clueweb_id
query_id
0               16420         16420      16420        16420  16420       16420
1               16633         16633      16633        16633  16633       16633
2               17061         17061      17061        17061  17061       17061
3               16252         16252      16252        16252  16252       16252
4               12049         12049      12049        12049  12049       12049
5               16149         16149      16149        16149  16149       16149
6               17300         17300      17300        17300  17300       17300
7               16675         16675      16675        16675  16675       16675
8               17541         17541      17541        17541  17541       17541
9               16227         16227      16227        16227  16227       16227
10              16084         16084      16084        16084  16084       16084
11              17628         17628      17628        17628  17628       17628
12              16706         16706      16706        16706  16706       16706
13              17925         17925      17925        17925  17925       17925
14              16316         16316      16316        16316  16316       16316
15              16132         16132      16132        16132  16132       16132
16              16687         16687      16687        16687  16687       16687
17              16994         16994      16994        16994  16994       16994
18              17801         17801      17801        17801  17801       17801
19              13213         13213      13213        13213  13213       13213
20              16523         16523      16523        16523  16523       16523
21              16239         16239      16239        16239  16239       16239
22              16295         16295      16295        16295  16295       16295
23              16098         16098      16098        16098  16098       16098
24              16357         16357      16357        16357  16357       16357
25              16285         16285      16285        16285  16285       16285
26              16564         16564      16564        16564  16564       16564
27              12657         12657      12657        12657  12657       12657
28              17141         17141      17141        17141  17141       17141
29              16851         16851      16851        16851  16851       16851
30              16603         16603      16603        16603  16603       16603
31              16342         16342      16342        16342  16342       16342
32              17247         17247      17247        17247  17247       17247
33              18322         18322      18322        18322  18322       18322
34              16832         16832      16832        16832  16832       16832
35              16347         16347      16347        16347  16347       16347
36              16402         16402      16402        16402  16402       16402
37              11834         11834      11834        11834  11834       11834
38              16829         16829      16829        16829  16829       16829
39              16347         16347      16347        16347  16347       16347
40              17274         17274      17274        17274  17274       17274
41              17145         17145      17145        17145  17145       17145
42              16147         16147      16147        16147  16147       16147
43              17688         17688      17688        17688  17688       17688
44              16610         16610      16610        16610  16610       16610
45              16991         16991      16991        16991  16991       16991
46              14645         14645      14645        14645  14645       14645
47              16710         16710      16710        16710  16710       16710
48              16216         16216      16216        16216  16216       16216
49              16454         16454      16454        16454  16454       16454
50              16659         16659      16659        16659  16659       16659
51              14642         14642      14642        14642  14642       14642
52               9513          9513       9513         9513   9513        9513
53              16405         16405      16405        16405  16405       16405
54              12931         12931      12931        12931  12931       12931
55              17215         17215      17215        17215  17215       17215
56              16259         16259      16259        16259  16259       16259
57              16885         16885      16885        16885  16885       16885
58              16358         16358      16358        16358  16358       16358
59              16284         16284      16284        16284  16284       16284
60              17003         17003      17003        17003  17003       17003
61              16125         16125      16125        16125  16125       16125
62              16526         16526      16526        16526  16526       16526
63              15984         15984      15984        15984  15984       15984
64              17254         17254      17254        17254  17254       17254
65              16115         16115      16115        16115  16115       16115
66              16702         16702      16702        16702  16702       16702
67               9144          9144       9144         9144   9144        9144
68              16189         16189      16189        16189  16189       16189
69               9394          9394       9394         9394   9394        9394
70              12632         12632      12632        12632  12632       12632
71              16204         16204      16204        16204  16204       16204
72              16204         16204      16204        16204  16204       16204
73              16714         16714      16714        16714  16714       16714
74              16206         16206      16206        16206  16206       16206
75              16283         16283      16283        16283  16283       16283
76              16002         16002      16002        16002  16002       16002
77              16457         16457      16457        16457  16457       16457
78              16454         16454      16454        16454  16454       16454
79              16811         16811      16811        16811  16811       16811
80              16147         16147      16147        16147  16147       16147
81              16562         16562      16562        16562  16562       16562
82              16341         16341      16341        16341  16341       16341
83              16452         16452      16452        16452  16452       16452
84              16359         16359      16359        16359  16359       16359
85              16213         16213      16213        16213  16213       16213
86              15764         15764      15764        15764  15764       15764
87              16126         16126      16126        16126  16126       16126
88              16651         16651      16651        16651  16651       16651
89              16209         16209      16209        16209  16209       16209
90              16210         16210      16210        16210  16210       16210
91              16261         16261      16261        16261  16261       16261
92              16673         16673      16673        16673  16673       16673
93              15924         15924      15924        15924  15924       15924
94              15871         15871      15871        15871  15871       15871
95              16700         16700      16700        16700  16700       16700
96              16708         16708      16708        16708  16708       16708
97              16276         16276      16276        16276  16276       16276
98              16409         16409      16409        16409  16409       16409
99              14078         14078      14078        14078  14078       14078

In [17]:
retrievals_000_099_df[retrievals_000_099_df['query_id'] == 0].sort_values(['score_znorm'], ascending=[False])

,query_id,colbertx_id,doc_position,doc_score,score_znorm,part,clueweb_id
0,0,4138910,1,28.797396,3.723518,2,clueweb22-pt0000-86-19982_33
7,0,8157162,1,28.422802,3.516794,4,clueweb22-pt0001-70-06195_8
17,0,7828446,1,28.384157,3.495905,3,clueweb22-pt0001-63-03254_3
23,0,3392707,1,28.252335,3.415572,1,clueweb22-pt0000-71-04006_2
31,0,2325385,1,28.157360,3.364606,1,clueweb22-pt0000-48-18850_1
...,...,...,...,...,...,...,...
64444,0,1945538,239,17.481098,-2.347833,0,clueweb22-pt0000-40-11747_13
64443,0,9902341,216,17.501192,-2.362328,4,clueweb22-pt0002-17-00382_1
64445,0,1942854,240,17.241718,-2.475473,0,clueweb22-pt0000-40-10441_3
64448,0,5934918,318,17.176956,-2.555321,2,clueweb22-pt0001-23-16351_0
64449,0,9908505,217,16.859024,-2.708008,4,clueweb22-pt0002-19-00373_6

In [18]:
retrievals_100_199_df = pd.read_csv(os.path.join(RETRIEVALS_FOLDER, "colbertx_all_znormalized_validation_scores_100_199.tsv"), sep='\t')

In [19]:
np.sort(retrievals_100_199_df['query_id'].unique())

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [21]:
retrievals_100_199_df['query_id'].unique().shape

(100,)

#### Save a single file with both queries set

In [23]:
colbertx_merged_df = pd.concat([retrievals_000_099_df, retrievals_100_199_df])

In [25]:
np.sort(colbertx_merged_df['query_id'].unique()).shape

(200,)

In [26]:
colbertx_merged_df.to_csv(os.path.join(RETRIEVALS_FOLDER, "colbertx_all_znormalized_validation_scores_000_199.tsv"), sep='\t', index=False)

#### Now compare the top_k documents returned by mT5 and Colbertx

In [ ]:
top_k=10

results = []

for group_name, group_df in mT5_df.groupby('query_id', sort=False):
    
    print("Handling query {}...".format(group_name))
    
    mT5_docs = group_df.iloc[:top_k]['doc_id'].to_numpy()
    
    if group_name >= 100:
        colbertx_docs = retrievals_100_199_df[retrievals_100_199_df['query_id'] == group_name].sort_values(['score_znorm'], ascending=[False]).iloc[:top_k]['clueweb_id'].to_numpy()
    else:
        colbertx_docs = retrievals_000_099_df[retrievals_000_099_df['query_id'] == group_name].sort_values(['score_znorm'], ascending=[False]).iloc[:top_k]['clueweb_id'].to_numpy()
        
    common_docs = np.intersect1d(mT5_docs, colbertx_docs)
        
    results.append({'query_id': group_name,
                    'mT5_docs': np.sort(mT5_docs),
                    'colbertx_docs': np.sort(colbertx_docs),
                    'mt5_colbertx_common_docs': np.sort(common_docs),
                    'mt5_colbertx_common_proportion': common_docs.shape[0] / top_k})

In [ ]:
results_df = pd.DataFrame(results)

In [ ]:
results_df

In [ ]:
results_df['mt5_colbertx_common_proportion'].describe()

### SPLADE retrievals

In [29]:
splade_df = pd.read_csv(os.path.join(RETRIEVALS_FOLDER, "splade_pt_result.txt"), sep=" ", names=['query_id', 'Q0', 'colbertx_id', 'position', 'score', 'comment'])

In [30]:
splade_df

        query_id  Q0  colbertx_id  position     score    comment
0              0  Q0      6124160         1 18.215471  SPLADE-PT
1              0  Q0      9394964         2 18.258245  SPLADE-PT
2              0  Q0       319340         3 17.736769  SPLADE-PT
3              0  Q0      9709254         4 18.771622  SPLADE-PT
4              0  Q0      5123052         5 17.621876  SPLADE-PT
...          ...  ..          ...       ...       ...        ...
199995       199  Q0      3132292       996 12.457484  SPLADE-PT
199996       199  Q0      1040828       997 12.447216  SPLADE-PT
199997       199  Q0      6319849       998 12.439510  SPLADE-PT
199998       199  Q0      5391434       999 12.460681  SPLADE-PT
199999       199  Q0      4831616      1000 12.433900  SPLADE-PT

[200000 rows x 6 columns]

In [33]:
id_conversion_df = pd.read_csv(os.path.join(COLBERTX_FOLDER, "clueweb22-pt_colbertx_to_clueweb_id.tsv"), sep="\t", names=['colbertx_id', 'clueweb_id'])

In [34]:
id_conversion_df.head()

   colbertx_id                   clueweb_id
0            0  clueweb22-pt0000-00-00001_0
1            1  clueweb22-pt0000-00-00001_1
2            2  clueweb22-pt0000-00-00001_4
3            3  clueweb22-pt0000-00-00001_5
4            4  clueweb22-pt0000-00-00003_0

In [35]:
splade_df = splade_df.merge(id_conversion_df)

In [36]:
splade_df.head()

,query_id,Q0,colbertx_id,position,score,comment,clueweb_id
0,0,Q0,6124160,1,18.215471,SPLADE-PT,clueweb22-pt0001-27-16321_1
1,0,Q0,9394964,2,18.258245,SPLADE-PT,clueweb22-pt0001-97-01569_0
2,1,Q0,9394964,706,18.854155,SPLADE-PT,clueweb22-pt0001-97-01569_0
3,68,Q0,9394964,921,18.207718,SPLADE-PT,clueweb22-pt0001-97-01569_0
4,0,Q0,319340,3,17.736769,SPLADE-PT,clueweb22-pt0000-06-04821_0

#### Save SPLADE QRel with the original clueweb document ID

In [38]:
splade_df.to_csv(os.path.join(RETRIEVALS_FOLDER, "splade_pt_result_with_clueweb_id.tsv"), sep='\t', index=False)

#### Now compare the top_k documents returned by mT5, Colbertx and SPLADE

In [ ]:
top_k=10

results_splade = []

i = 0

for group_name, group_df in mT5_df.groupby('query_id', sort=False):
    
    print("Handling query {}...".format(group_name))
    
    mT5_docs = group_df.iloc[:top_k]['doc_id'].to_numpy()
    
    splade_docs = splade_df[splade_df['query_id'] == group_name].sort_values(['score'], ascending=[False]).iloc[:top_k]['clueweb_id'].to_numpy()
        
    mt5_splade_common_docs = np.intersect1d(mT5_docs, splade_docs)
    colbertx_splade_common_docs = np.intersect1d(results[i]['colbertx_docs'], splade_docs)
    
    common_docs = np.intersect1d(mt5_splade_common_docs, colbertx_splade_common_docs)
    
    results_splade.append({'query_id': group_name,
                           'mT5_docs': np.sort(mT5_docs),
                           'colbertx_docs': np.sort(splade_docs),
                           'mt5_splade_common_docs': np.sort(mt5_splade_common_docs),
                           'mt5_splade_common_proportion': mt5_splade_common_docs.shape[0] / top_k,
                           'colbertx_splade_common_docs': np.sort(colbertx_splade_common_docs),
                           'colbertx_splade_common_proportion': colbertx_splade_common_docs.shape[0] / top_k,
                           'common_docs': np.sort(common_docs),
                           'common_proportion': common_docs.shape[0] / top_k
                          })
    i += 1

In [ ]:
results_splade_df = pd.DataFrame(results_splade)

In [ ]:
results_splade_df

In [ ]:
results_splade_df['mt5_splade_common_proportion'].describe()

In [ ]:
results_splade_df['colbertx_splade_common_proportion'].describe()

In [ ]:
results_splade_df['common_proportion'].describe()